version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-1.23-bookworm
    ports:
      - "19132:19132/udp"
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
